export default defineEventHandler((e) => {
  return [
    "React",
    "Javascript",
    "Python",
    "HTML",
    "CSS",
    "C",
    "C++",
    "Java",
    "JavaScript",
    "TypeScript",
    "HTML/CSS",
    "SQL",
    "Shell Scripting (Bash)",
    "Powershell",
    "Go",
    "Rust",
    "C#",
    "Ruby",
    "Swift",
    "Kotlin",
    "PHP",
    "Typescript",
    "R",
    "Dart",
    "Scala",
    "Perl",
    "Haskell",
    "Lua",
    "Elixir",
    "Objective-C",
    "Angular",
    "Vue.js",
    "Django",
    "Flask",
    "Spring",
    "Ruby on Rails",
    "Laravel",
    "Express.js",
    "TensorFlow",
    "Bootstrap",
    "jQuery",
    "Next.js",
    "Nuxt.js",
    "Svelte",
    "ASP.NET",
    "Keras",
    "Hibernate",
    "Redux",
    "Tailwind CSS",
    "Electron",
    "Gatsby",
    "Ember.js",
    "Backbone.js",
    "Material-UI",
    "Chakra UI",
    "Three.js",
    "FastAPI",
    "Pandas",
    "BeautifulSoup",
    "Play Framework",
    "Symfony",
    "CodeIgniter",
    "Xamarin",
    "Phoenix",
    "RxJava",
    "Alpine.js",
    "GraphQL",
    "Mockito",
    "Sequelize",
    "Mongoose",
    "Webpack",
    "Parcel",
    "Grunt",
    "Gulp",
    "Sinatra",
    "Lodash",
    "Underscore.js",
    "NestJS",
    "React Native",
    "Vuex",
    "Pylons",
    "Tornado",
    "Pyramid",
    "Dropwizard",
    "Vaadin",
    "jQuery UI",
    "Cocoa Touch",
    "PyTorch",
    "MATLAB",
    "Groovy",
    "Erlang",
    "Clojure",
    "F#",
    "VHDL",
    "Fortran",
    "Ada",
    "Assembly Language",
    "COBOL",
    "Prolog",
    "Smalltalk",
    "Scheme",
    "Julia",
    "Tcl",
    "Simula",
    "Pascal",
    "ABAP",
    "OCaml",
    "Solidity",
    "Racket",
    "Nim",
    "Crystal",
    "Forth",
    "ActionScript",
    "Vala",
    "D",
    "Logo",
    "CoffeeScript",
    "MongoDB",
    "Git",
    "RESTful API Development",
    "Microservices Architecture",
    "Docker",
    "Kubernetes",
    "CI/CD Pipelines",
    "AWS Cloud Services",
    "Azure Cloud Services",
    "Google Cloud Platform",
    "Agile Methodologies",
    "Scrum Framework",
    "Unit Testing",
    "Integration Testing",
    "Test-Driven Development",
    "Behavior-Driven Development",
    "Continuous Integration",
    "Continuous Deployment",
    "Containerization",
    "Linux/Unix Command Line",
    "Puppet/Chef/Ansible",
    "Terraform",
    "Serverless Architecture",
    "API Gateway",
    "Firebase",
    "Node.js",
    "WebSocket",
    "Authentication Protocols (OAuth, JWT)",
    "GraphQL API Development",
    "Web Security (e.g., XSS, CSRF)",
    "SSL/TLS",
    "HTTP/HTTPS Protocols",
    "Load Balancing",
    "Reverse Proxy",
    "Apache/Nginx",
    "Stored Procedures",
    "Big Data Technologies (e.g., Hadoop, Spark)",
    "Machine Learning (e.g., TensorFlow, PyTorch)",
    "Data Mining",
    "Natural Language Processing (NLP)",
    "Computer Vision",
    "Artificial Intelligence (AI)",
    "Blockchain Technology",
    "Cryptography",
    "Software Design Patterns",
    "Object-Oriented Programming (OOP)",
    "Functional Programming",
    "Domain-Driven Design (DDD)",
    "Event-Driven Architecture",
    "Message Brokers (e.g. RabbitMQ, Kafka)",
    "Elasticsearch",
    "Redis",
    "Graph Databases (e.g. Neo4j)",
    "Mobile App Development (iOS/Android)",
    "Flutter",
    "Responsive Web Design",
    "Cross-Browser Compatibility",
    "Web Performance Optimization",
    "Progressive Web Apps (PWAs)",
    "Single Page Applications (SPAs)",
    "Electron.js",
    "WebAssembly",
    "gRPC",
    "API Documentation (e.g. Swagger, OpenAPI)",
    "Embedded Systems",
    "Firmware Development",
    "IoT Development",
    "Automated Testing (e.g. Selenium, Cypress)",
    "Load Testing (e.g. JMeter)",
    "Penetration Testing",
    "Vulnerability Scanning",
  ];
});
