export default defineEventHandler((e) => {
  return [
    "React",
    "Javascript",
    "Python",
    "HTML",
    "CSS",
    "C",
    "C++",
    "Java",
    "Typescript",
    "SQL",
    "Shell Scripting (Bash)",
    "Powershell",
    "Go",
    "Rust",
    "C#",
    "Ruby",
    "Swift",
    "Kotlin",
    "PHP",
    "R",
    "Dart",
    "Scala",
    "Perl",
    "Haskell",
    "Lua",
    "Elixir",
    "Objective-C",
    "Angular",
    "Vue.js",
    "Django",
    "Flask",
    "Spring",
    "Ruby on Rails",
    "Laravel",
    "Express.js",
    "TensorFlow",
    "Bootstrap",
    "jQuery",
    "Next.js",
    "Nuxt.js",
    "Svelte",
    "ASP.NET",
    "Keras",
    "Hibernate",
    "Redux",
    "Tailwind CSS",
    "Electron",
    "Gatsby",
    "Ember.js",
    "Backbone.js",
    "Material-UI",
    "Chakra UI",
    "Three.js",
    "FastAPI",
    "Pandas",
    "BeautifulSoup",
    "Play Framework",
    "Symfony",
    "CodeIgniter",
    "Xamarin",
    "Phoenix",
    "RxJava",
    "Alpine.js",
    "GraphQL",
    "Mockito",
    "Sequelize",
    "Mongoose",
    "Webpack",
    "Parcel",
    "Grunt",
    "Gulp",
    "Sinatra",
    "Lodash",
    "Underscore.js",
    "NestJS",
    "React Native",
    "Vuex",
    "Pylons",
    "Tornado",
    "Pyramid",
    "Dropwizard",
    "Vaadin",
    "jQuery UI",
    "Cocoa Touch",
    "PyTorch",
    "MATLAB",
    "Groovy",
    "Erlang",
    "Clojure",
    "F#",
    "VHDL",
    "Fortran",
    "Ada",
    "Assembly Language",
    "COBOL",
    "Prolog",
    "Smalltalk",
    "Scheme",
    "Julia",
    "Tcl",
    "Simula",
    "Pascal",
    "ABAP",
    "OCaml",
    "Solidity",
    "Racket",
    "Nim",
    "Crystal",
    "Forth",
    "ActionScript",
    "Vala",
    "D",
    "Logo",
    "CoffeeScript",
    "MongoDB",
    "Git",
    "RESTful API Development",
    "Microservices Architecture",
    "Docker",
    "Kubernetes",
    "CI/CD Pipelines",
    "AWS Cloud Services",
    "Azure Cloud Services",
    "Google Cloud Platform",
    "Agile Methodologies",
    "Scrum Framework",
    "Unit Testing",
    "Integration Testing",
    "Test-Driven Development",
    "Behavior-Driven Development",
    "Continuous Integration",
    "Continuous Deployment",
    "Containerization",
    "Linux/Unix Command Line",
    "Puppet/Chef/Ansible",
    "Terraform",
    "Serverless Architecture",
    "API Gateway",
    "Firebase",
    "Node.js",
    "WebSocket",
    "Authentication Protocols (OAuth, JWT)",
    "GraphQL API Development",
    "Web Security (e.g., XSS, CSRF)",
    "SSL/TLS",
    "HTTP/HTTPS Protocols",
    "Load Balancing",
    "Semantic Versioning",
  ];
});
